# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .. import util


class Pet(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(
        self, id: int = None, name: str = None, breed: str = None, price: float = None
    ):  # noqa: E501
        """Pet - a model defined in Swagger

        :param id: The id of this Pet.  # noqa: E501
        :type id: int
        :param name: The name of this Pet.  # noqa: E501
        :type name: str
        :param breed: The breed of this Pet.  # noqa: E501
        :type breed: str
        :param price: The price of this Pet.  # noqa: E501
        :type price: float
        """
        self.swagger_types = {"id": int, "name": str, "breed": str, "price": float}

        self.attribute_map = {
            "id": "id",
            "name": "name",
            "breed": "breed",
            "price": "price",
        }

        self._id = id
        self._name = name
        self._breed = breed
        self._price = price

    @classmethod
    def from_dict(cls, dikt) -> "Pet":
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Pet of this Pet.  # noqa: E501
        :rtype: Pet
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Pet.


        :return: The id of this Pet.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Pet.


        :param id: The id of this Pet.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Pet.


        :return: The name of this Pet.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Pet.


        :param name: The name of this Pet.
        :type name: str
        """
        if name is None:
            raise ValueError(
                "Invalid value for `name`, must not be `None`"
            )  # noqa: E501

        self._name = name

    @property
    def breed(self) -> str:
        """Gets the breed of this Pet.


        :return: The breed of this Pet.
        :rtype: str
        """
        return self._breed

    @breed.setter
    def breed(self, breed: str):
        """Sets the breed of this Pet.


        :param breed: The breed of this Pet.
        :type breed: str
        """
        if breed is None:
            raise ValueError(
                "Invalid value for `breed`, must not be `None`"
            )  # noqa: E501

        self._breed = breed

    @property
    def price(self) -> float:
        """Gets the price of this Pet.


        :return: The price of this Pet.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this Pet.


        :param price: The price of this Pet.
        :type price: float
        """
        if price is None:
            raise ValueError(
                "Invalid value for `price`, must not be `None`"
            )  # noqa: E501

        self._price = price
